# data
data:
  instruct_data: "data/updated_train.jsonl"
  eval_instruct_data: "data/val.jsonl"

# model
model_id_or_path: "/mnt/nvme/home/shared_models/huggingface/mistralai/Mistral-Nemo-Instruct-2407"  # Change to downloaded path
lora:
  rank: 64

# optim
seq_len: 12000
batch_size: 1
max_steps: 400
num_microbatches: 4
optim:
  lr: 1.e-4
  weight_decay: 0.1
  pct_start: 0.05

# other
seed: 42
log_freq: 1
eval_freq: 40
no_eval: False
ckpt_freq: 40
num_ckpt_keep: null

save_adapters: True  # save only trained LoRA adapters. Set to `False` to merge LoRA adapter into the base model and save full fine-tuned model

run_dir: "run-v2"  # Fill

wandb:
  project: "system-finetune" # your wandb project name
  run_name: "nemo-v2" # your wandb run name
  key: "" # your wandb api key
  offline: False
