# data
data:
  instruct_data: "data/ultra_lowercase_train_new.jsonl"
  eval_instruct_data: "data/ultra_lowercase_val_new.jsonl"

# model
model_id_or_path: "/scratch/public_models/huggingface/mistralai/Mistral-7B-Instruct-v0.3"  # Change to downloaded path
lora:
  rank: 16

# optim
seq_len: 8192
batch_size: 1
max_steps: 220
num_microbatches: 4
optim:
  lr: 2.e-5
  weight_decay: 0.001
  pct_start: 0.05

# other
seed: 42
log_freq: 1
eval_freq: 20
no_eval: False
ckpt_freq: 20
num_ckpt_keep: null

save_adapters: True  # save only trained LoRA adapters. Set to `False` to merge LoRA adapter into the base model and save full fine-tuned model

run_dir: "runs/ultra-lowercase-prefix"  # Fill

wandb:
  project: "mistral-lowercase" # your wandb project name
  run_name: "ultra-lowercase-prefix" # your wandb run name
  key: "" # your wandb api key
  offline: False
